### ISSUE TITLE
[Bug]: appium is giving Error "Failed to instantiate remote driver instance"

### ISSUE THREAD

**Issue by Salma2018170** [ShaftHQ/SHAFT_ENGINE#938] opened 2023-03-08 13:14 UTC
shaft v7.1.20230227 
Appium 2
android real device 

[3b5794f1be2138a2.txt](https://github.com/ShaftHQ/SHAFT_ENGINE/files/10919715/3b5794f1be2138a2.txt)
![image](https://user-images.githubusercontent.com/76792591/223692867-4e639e70-f430-4065-80ab-1feb76280fd8.png)
![image](https://user-images.githubusercontent.com/76792591/223722293-dec77cec-0e05-4f7b-a5e5-664017a7bbbc.png)
![image](https://user-images.githubusercontent.com/76792591/223722426-a6f761c2-c0f3-4182-ab49-cf03d4a7880f.png)

**Comment by MohabMohie** [comment] 2023-03-11 08:15
the attached logs show this error message

```java
[DEBUG] 2023-03-08 12:07:45.105 [main] ReportManager - org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: 'automationName' can't be blank 
```

please make sure to setup automationName properly, here's a working sample for reference:

```java
SHAFT.Properties.platform.set().targetPlatform(Platform.ANDROID.name());
SHAFT.Properties.mobile.set().automationName(AutomationName.ANDROID_UIAUTOMATOR2);
SHAFT.Properties.platform.set().executionAddress("localhost:4723");
```

also please note that it is within appium best practices to use `appUrl` rather than `appName` and `appPackage`, here's a working sample for that as well:

```java
SHAFT.Properties.mobile.set().app("src/test/resources/testDataFiles/apps/ApiDemos-debug.apk");
```

lastly you are strongly advised to use the SHAFT wizard syntax instead as it provides enhanced sessions management and stability, you can read more about it in our [official user guide](https://shafthq.github.io/SHAFT_Engine_Docusaurus/docs/Keywords/GUI/Browser_Actions), and here's a full working sample:

```java
private SHAFT.GUI.WebDriver driver;

@BeforeMethod
public void setup() {
    // common attributes
    SHAFT.Properties.platform.set().targetPlatform(Platform.ANDROID.name());
    SHAFT.Properties.mobile.set().automationName(AutomationName.ANDROID_UIAUTOMATOR2);
    SHAFT.Properties.platform.set().executionAddress("localhost:4723");
    SHAFT.Properties.mobile.set().app("src/test/resources/testDataFiles/apps/ApiDemos-debug.apk");
}

@AfterMethod(alwaysRun = true)
public void teardown() {
    driver.quit();
}

@Test
public void wizard_scrollInExpandableLists_verticalScrolling_insideScreen() {
    ((AndroidDriver) driver.getDriver()).runAppInBackground(Duration.ofSeconds(5));
    driver.element().performTouchAction()
            .swipeElementIntoView(AppiumBy.accessibilityId("Views"), TouchActions.SwipeDirection.DOWN)
            .tap(AppiumBy.accessibilityId("Views"))
            .swipeElementIntoView(AppiumBy.accessibilityId("Expandable Lists"), TouchActions.SwipeDirection.DOWN)
            .tap(AppiumBy.accessibilityId("Expandable Lists"))
            .swipeElementIntoView(AppiumBy.accessibilityId("3. Simple Adapter"), TouchActions.SwipeDirection.DOWN)
            .tap(AppiumBy.accessibilityId("3. Simple Adapter"))
            .swipeElementIntoView(By.xpath("//android.widget.TextView[@text='Group 18']"), TouchActions.SwipeDirection.DOWN)
            .tap(By.xpath("//android.widget.TextView[@text='Group 18']"))
            .swipeElementIntoView(By.xpath("//android.widget.TextView[@text='Child 13']"), TouchActions.SwipeDirection.DOWN)
            .swipeElementIntoView(By.xpath("//android.widget.TextView[@text='Group 1']"), TouchActions.SwipeDirection.UP);
}

```

I'm closing this as it's not a bug, but kindly feel free to open new issues whenever you need support with something.

**Closed by MohabMohie** 2023-03-11 08:15 UTC
Labels: bug, triage
