### ISSUE TITLE
[Bug]: while running a test class that has a test case with @Issue annotation this test case is skipped 

### ISSUE THREAD

**Issue by ahmedtalaat-8** [ShaftHQ/SHAFT_ENGINE#1349] opened 2023-10-30 08:36 UTC
I'm facing an issue while running a test class that has a test case with @issue annotation , this test case is displayed in the report as a skipped test case despite having the skipTestsWithLinkedIssues = false - by default it's false - 
current version : 7.4.20231026
it was working on previous version : 7.3.20230829
![image](https://github.com/ShaftHQ/SHAFT_ENGINE/assets/75179737/c57abbff-5800-4e18-9ecc-30ffa215fd6c)

**Comment by MahmoudElSharkawy** [comment] 2023-10-31 08:49
After investigation, the issue is caused because of this flag here in the `select `method.
https://github.com/ShaftHQ/SHAFT_ENGINE/blob/main/src/main/java/com/shaft/gui/element/ElementActions.java#L710-L711

**Comment by MahmoudElSharkawy** [comment] 2023-11-12 11:54
Fixed by this PR #1350

**Closed by MahmoudElSharkawy** 2023-11-12 11:54 UTC
Labels: bug, triage
