### ISSUE TITLE
Web GUI >>Element Actions >> type method issue

### ISSUE THREAD

**Issue by KyrillosNageh** [ShaftHQ/SHAFT_ENGINE#786] opened 2022-12-07 20:43 UTC
**Describe the bug**
when trying to use the type function to write something in fields like date, It is cleared after it was written.

**To Reproduce**
1. download the project and execute it.
https://github.com/KyrillosNageh/E-Commerce_Jumia/tree/main/JumiaProjectUsingSHAFT_Engine

**Screen Record**
https://user-images.githubusercontent.com/109525267/206289849-c1dc1329-7214-4434-bc76-48e1a2ffcd18.mp4

@MohabMohie

**Comment by MohabMohie** [comment] 2022-12-11 06:29
I downloaded and ran it... and I cannot reproduce the issue
![image](https://user-images.githubusercontent.com/19201898/206889645-f0f8c609-830d-4bad-bff2-ed11b908099c.png)

I do think that there's an issue with the scenario though... I think you want to register a new account, but the scenario is attempting to login
![image](https://user-images.githubusercontent.com/19201898/206889687-3a597e69-ef35-4a9b-b508-ea251a499d87.png)

I'll close the issue for now, please provide a concise example to be able to reproduce it...
I mainly need minimum lines of code in a stand-alone file with two simple tests (not an entire repository please)
navigate / type (showing that native selenium works)
navigate / type (showing that shaft fails)

**Closed by MohabMohie** 2022-12-11 06:29 UTC
